#!/bin/bash

#Redirect output
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
# Log everything
#exec 1>/tmp/log.out 2>&1

#local TEST

# Array of test to run
declare -a arr=(
                "ping 1.1 -c 4 -q"
                "ping bbc.co.uk -c 4 -q"
                "ssh i -q -o "BatchMode=yes" -T git@github.com"
                )

echo starting Crappy pingtest script.. $date

# Loop through the array of test
for i in "${arr[@]}"
do
    TEST=$($i)
    RESPONSE=$?

# Actions to take on RESPONSE
if [[ $RESPONSE == 0 ]] ; then
  echo $i = OK
elif [[ $RESPONSE == "255" ]] ; then
  echo $i = OK
else
  echo $i = FAIL
fi

done

exit
