#!/bin/bash

declare -a buckets=(
"3orr009-npcug6h"
"3ye4ldu-srrhd4f6"
"amplify-amplifyea85c291bb134-staging-115046-deployment"
"appstream-app-settings-eu-west-2-651948078005-repng3m4"
"appstream2-36fb080bb8-eu-west-2-651948078005"
"aws-keys-rotate-into-github-secrets-instance-pem-key"
"cdk-hnb659fds-assets-651948078005-eu-west-2"
"cdk-hnb659fds-assets-651948078005-us-east-1"
"cf-templates-vl0bydwktp8u-eu-west-2"
"datadog-forwarder-forwarderbucket-1fuuzf2w8ssce"
"ofr-admin-pipeline-integ-ofradminpipelineintegrat-1rhqi6xxrgksr"
"ofr-admin-pipeline-integ-ofradminpipelineintegrat-gqheb91n1amu"
"ofr-fwa-application-inte-ofrfwaapplicationintegra-vsdex7hrp5ba"
"ofr-fwa-application-integration"
"ofr-fwa-application-of-5-ofrfwaapplicationof5912f-14cp275l2yl29"
"ofr-fwa-application-of-5-ofrfwaapplicationof5912f-1hrz51bz8tx6c"
"ofr-fwa-pipeline-integra-ofrfwapipelineintegratio-1nr77ku4k1pbw"
"ofr-fwa-pipeline-integra-ofrfwapipelineintegratio-4qtfo7zakqbk"
"ofr-fwa-pipeline-integra-ofrfwapipelineintegratio-ecprwfkulrij"
"ofr-fwa-pipeline-of-5912-ofrfwapipelineof5912pipe-1n9w70v4mfqzr"
"ofr-fws-application-inte-ofrfwsapplicationintegra-r48iu7e5ch2c"
"ofr-fws-application-inte-ofrfwsapplicationintegra-zbyajldjzweo"
"ofr-fws-application-integration"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-105sf3f7fm93a"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-14vxphrf3addt"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-1820we6ej44kt"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-1azau95assn7z"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-1dn01jx20p89f"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-1lxk1ee5f643x"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-1nu8f54gdv1dz"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-1p1f2l7i0btf8"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-1pvs2h4v9l3au"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-1qdoregi662ap"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-1ser2ovc53hz8"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-1t6qo5ush4eay"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-1xnzej7nwwv9g"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-2qkfau53elym"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-6vdbtawtxh29"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-8ikja63tafqf"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-9qwbo5ousioc"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-9xd6gju2db31"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-bh6or4gg9ekh"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-cletgr21o7o4"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-d6rsup8kei09"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-ec2gl0of9dvx"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-fc33iultaw6x"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-fcrk04audavi"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-g0ytlbfavqu7"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-gy7af0tb7fff"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-nsd1txjwi525"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-ozipxay74kty"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-pni677s2ebd7"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-v1xoew3h0kg5"
"ofr-fws-application-pull-ofrfwsapplicationpullreq-x85421czvxdm"
"ofr-fws-application-pull-request-of-6201"
"ofr-fws-integration-logs"
"ofr-fws-pipeline-integra-ofrfwspipelineintegratio-1dgxowptj79a"
"ofr-fws-pipeline-integra-ofrfwspipelineintegratio-guwwvr1uvhne"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-13s7p7p885k1q"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-14ytxzd06kpkp"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-16pn1p7zxloju"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-16sh74a09h6hz"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-180v9d3qmvpzd"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-18p3ouw2y75c6"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-1akgkomk9jixv"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-1alo1w4qxuqve"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-1arv2f3svzsm4"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-1civ74mlnft3u"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-1e47klumhe9wx"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-1iyxyhd1hhqd0"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-1kwbenk3e90ql"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-1nwak9c0mu78j"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-1qxctmo81jugt"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-1rxflj8zik7ef"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-1sxvuf4f412ke"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-1t1n23ybs1el"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-28xfqkr7jtel"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-2b3wujikfd40"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-6k9c0u3dbk1c"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-74wxmzabquco"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-7q9tjwnpfrb8"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-8vvo67ufus8h"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-99yg6zmogml2"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-9uew42s14ytn"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-bizwbf3gp74e"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-i8tk78rorhdv"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-jfswppjknfvq"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-k6fl56306az"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-kdazw5ex2rjy"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-ljwpjh8quade"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-mo2rffwkkzxh"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-ryhcgki5vfgk"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-thxr8sosqjfc"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-uwwp29z056x1"
"ofr-fws-pipeline-pull-re-ofrfwspipelinepullreques-wjngfhpsxu5b"
"stackset-datadogforwarderv1-85753-forwarderbucket-1lwp4rvgnvl3b"
)

outputfile=policy.json
#outputfile=acl.json
timestamp=$(date +"%m-%d-%y-%r")

echo $timestamp > $outputfile

for b in "${buckets[@]}"
do
    echo $b >> $outputfile
    aws s3api get-bucket-policy --bucket $b >> $outputfile
    #aws s3api get-bucket-acl --bucket $b >> $outputfile
done
